import { addDays, startOfWeek, toISODate } from "./date";
import type { Booking, Coach, Player, Profile, Review, Session, User } from "./types";

const baseWeek = startOfWeek(new Date());

const buildSlot = (dayOffset: number, time: string, durationMinutes = 60) => ({
  date: toISODate(addDays(baseWeek, dayOffset)),
  time,
  durationMinutes,
});

export const mockPlayer: Player = {
  id: "player_1",
  name: "Alex Martin",
  city: "Rouen",
  level: "Intermédiaire",
  position: "Milieu offensif",
  rating: 4.2,
  reviews: 8,
};

export const mockUsers: User[] = [
  { id: "user_1", email: "alex@performx.fr", role: "player", createdAt: new Date().toISOString() },
  { id: "user_10", email: "jean@performx.fr", role: "coach", createdAt: new Date().toISOString() },
  { id: "user_11", email: "philippe@performx.fr", role: "coach", createdAt: new Date().toISOString() },
  { id: "user_12", email: "sarah@performx.fr", role: "coach", createdAt: new Date().toISOString() },
  { id: "user_13", email: "kevin@performx.fr", role: "coach", createdAt: new Date().toISOString() },
  { id: "user_14", email: "amina@performx.fr", role: "coach", createdAt: new Date().toISOString() },
  { id: "user_15", email: "hugo@performx.fr", role: "coach", createdAt: new Date().toISOString() },
  { id: "user_16", email: "noa@performx.fr", role: "coach", createdAt: new Date().toISOString() },
  { id: "user_17", email: "lina@performx.fr", role: "coach", createdAt: new Date().toISOString() },
];

export const mockProfiles: Profile[] = [
  { userId: "user_1", firstName: "Alex", lastName: "Martin", city: "Rouen" },
  { userId: "user_10", firstName: "Jean", lastName: "Dupont", city: "Rouen" },
  { userId: "user_11", firstName: "Philippe", lastName: "Le Divert", city: "Le Havre" },
  { userId: "user_12", firstName: "Sarah", lastName: "Mbappé", city: "Caen" },
  { userId: "user_13", firstName: "Kevin", lastName: "Morel", city: "Évreux" },
  { userId: "user_14", firstName: "Amina", lastName: "Reza", city: "Rouen" },
  { userId: "user_15", firstName: "Hugo", lastName: "Lambert", city: "Dieppe" },
  { userId: "user_16", firstName: "Noa", lastName: "El Mahdi", city: "Rouen" },
  { userId: "user_17", firstName: "Lina", lastName: "Pereira", city: "Fécamp" },
];

export const mockCoaches: Coach[] = [
  {
    id: "coach_1",
    userId: "user_10",
    name: "Jean Dupont",
    speciality: "Coach technique",
    bio: "Ancien joueur professionnel, focus sur la précision et le contrôle du ballon.",
    location: "Rouen · 12 km",
    pricePerSession: 39,
    rating: 4.7,
    reviews: 52,
    availability: [
      buildSlot(1, "18:00"),
      buildSlot(2, "19:30"),
      buildSlot(4, "17:00"),
    ],
  },
  {
    id: "coach_2",
    userId: "user_11",
    name: "Philippe Le Divert",
    speciality: "Préparation physique",
    bio: "Travail vitesse, explosivité et prévention des blessures.",
    location: "Le Havre · 25 km",
    pricePerSession: 55,
    rating: 4.3,
    reviews: 38,
    availability: [
      buildSlot(1, "20:00"),
      buildSlot(3, "18:30"),
      buildSlot(5, "10:00"),
    ],
  },
  {
    id: "coach_3",
    userId: "user_12",
    name: "Sarah Mbappé",
    speciality: "Gardienne",
    bio: "Spécialiste du jeu aérien et des réflexes rapides.",
    location: "Caen · 18 km",
    pricePerSession: 45,
    rating: 4.9,
    reviews: 64,
    availability: [
      buildSlot(2, "16:00"),
      buildSlot(4, "19:00"),
      buildSlot(6, "11:00"),
    ],
  },
  {
    id: "coach_4",
    userId: "user_13",
    name: "Kevin Morel",
    speciality: "Vision de jeu",
    bio: "Séances personnalisées pour améliorer la prise d'informations.",
    location: "Évreux · 33 km",
    pricePerSession: 42,
    rating: 4.6,
    reviews: 29,
    availability: [
      buildSlot(0, "17:30"),
      buildSlot(2, "18:00"),
      buildSlot(3, "20:00"),
    ],
  },
  {
    id: "coach_5",
    userId: "user_14",
    name: "Amina Reza",
    speciality: "Frappe",
    bio: "Travail de finition, placement et gestes techniques avancés.",
    location: "Rouen · 8 km",
    pricePerSession: 48,
    rating: 4.8,
    reviews: 47,
    availability: [
      buildSlot(1, "17:00"),
      buildSlot(2, "19:00"),
      buildSlot(4, "18:30"),
    ],
  },
  {
    id: "coach_6",
    userId: "user_15",
    name: "Hugo Lambert",
    speciality: "Endurance",
    bio: "Plan personnalisé pour progresser sur 90 minutes.",
    location: "Dieppe · 40 km",
    pricePerSession: 35,
    rating: 4.2,
    reviews: 19,
    availability: [
      buildSlot(0, "08:30"),
      buildSlot(5, "09:30"),
    ],
  },
  {
    id: "coach_7",
    userId: "user_16",
    name: "Noa El Mahdi",
    speciality: "Dribbles",
    bio: "Travail coordination, feintes et changements de rythme.",
    location: "Rouen · 14 km",
    pricePerSession: 50,
    rating: 4.9,
    reviews: 71,
    availability: [
      buildSlot(1, "16:30"),
      buildSlot(3, "19:00"),
      buildSlot(5, "14:00"),
    ],
  },
  {
    id: "coach_8",
    userId: "user_17",
    name: "Lina Pereira",
    speciality: "Jeu défensif",
    bio: "Placement, interventions et lecture du jeu.",
    location: "Fécamp · 55 km",
    pricePerSession: 38,
    rating: 4.4,
    reviews: 22,
    availability: [
      buildSlot(2, "17:00"),
      buildSlot(6, "15:00"),
    ],
  },
];

export const mockPlayers: Player[] = [
  {
    id: "player_1",
    name: "Alex Martin",
    city: "Rouen",
    level: "Intermédiaire",
    position: "Milieu offensif",
    objectives: "Améliorer ma vision de jeu et mes passes décisives.",
    rating: 4.2,
    reviews: 8,
  },
  {
    id: "player_2",
    name: "Lucas Bertin",
    city: "Rouen",
    level: "Avancé",
    position: "Attaquant",
    objectives: "Travailler la finition et les frappes enroulées.",
    rating: 4.5,
    reviews: 14,
  },
  {
    id: "player_3",
    name: "Inès Chabane",
    city: "Le Havre",
    level: "Débutant",
    position: "Défenseur central",
    objectives: "Gagner en confiance et améliorer mon placement.",
    rating: 3.8,
    reviews: 3,
  },
  {
    id: "player_4",
    name: "Mathis Lefèvre",
    city: "Caen",
    level: "Intermédiaire",
    position: "Gardien",
    objectives: "Développer mes réflexes et mon jeu au pied.",
    rating: 4.0,
    reviews: 6,
  },
  {
    id: "player_5",
    name: "Yasmine El Amrani",
    city: "Évreux",
    level: "Avancé",
    position: "Milieu défensif",
    objectives: "Gagner en endurance et en pressing haut.",
    rating: 4.7,
    reviews: 19,
  },
  {
    id: "player_6",
    name: "Théo Garnier",
    city: "Dieppe",
    level: "Débutant",
    position: "Ailier droit",
    objectives: "Apprendre les bases du dribble et des centres.",
    rating: 3.5,
    reviews: 2,
  },
  {
    id: "player_7",
    name: "Chloé Da Silva",
    city: "Rouen",
    level: "Intermédiaire",
    position: "Latéral gauche",
    objectives: "Améliorer les montées offensives et les centres.",
    rating: 4.3,
    reviews: 11,
  },
  {
    id: "player_8",
    name: "Rayan Benali",
    city: "Fécamp",
    level: "Avancé",
    position: "Meneur de jeu",
    objectives: "Perfectionner les coups de pied arrêtés.",
    rating: 4.6,
    reviews: 22,
  },
];

export const mockSessions: Session[] = [
  {
    id: "session_1",
    coachId: "coach_1",
    playerId: mockPlayer.id,
    title: "Entraînement tir au but",
    date: toISODate(addDays(baseWeek, 1)),
    time: "18:00",
    durationMinutes: 60,
    status: "upcoming",
  },
  {
    id: "session_2",
    coachId: "coach_1",
    playerId: mockPlayer.id,
    title: "Entraînement précision",
    date: toISODate(addDays(baseWeek, 3)),
    time: "19:30",
    durationMinutes: 60,
    status: "upcoming",
  },
  {
    id: "session_3",
    coachId: "coach_5",
    playerId: mockPlayer.id,
    title: "Endurance fondamentale",
    date: toISODate(addDays(baseWeek, -3)),
    time: "18:30",
    durationMinutes: 60,
    status: "completed",
  },
  {
    id: "session_4",
    coachId: "coach_4",
    playerId: mockPlayer.id,
    title: "Motricité & Proprioception",
    date: toISODate(addDays(baseWeek, -7)),
    time: "17:00",
    durationMinutes: 60,
    status: "completed",
  },
];

export const mockBookings: Booking[] = [
  {
    id: "booking_1",
    sessionId: "session_1",
    playerId: mockPlayer.id,
    coachId: "coach_1",
    createdAt: new Date().toISOString(),
    price: 39,
    paymentStatus: "paid",
  },
  {
    id: "booking_2",
    sessionId: "session_2",
    playerId: mockPlayer.id,
    coachId: "coach_1",
    createdAt: new Date().toISOString(),
    price: 39,
    paymentStatus: "paid",
  },
];

export const mockReviews: Review[] = [
  {
    id: "review_1",
    coachId: "coach_1",
    playerName: "Lucas B.",
    rating: 5,
    comment: "Séance ultra précise, j'ai gagné en contrôle de balle dès la première semaine.",
    date: toISODate(addDays(baseWeek, -10)),
  },
  {
    id: "review_2",
    coachId: "coach_1",
    playerName: "Amine K.",
    rating: 4,
    comment: "Coach exigeant mais efficace, je recommande.",
    date: toISODate(addDays(baseWeek, -18)),
  },
  {
    id: "review_3",
    coachId: "coach_2",
    playerName: "Sarah M.",
    rating: 4,
    comment: "Super préparation physique, j'ai senti la diff sur le terrain.",
    date: toISODate(addDays(baseWeek, -6)),
  },
  {
    id: "review_4",
    coachId: "coach_3",
    playerName: "Jules R.",
    rating: 5,
    comment: "Top pour les gardiens, beaucoup de situations réelles.",
    date: toISODate(addDays(baseWeek, -14)),
  },
  {
    id: "review_5",
    coachId: "coach_4",
    playerName: "Nora S.",
    rating: 4,
    comment: "Très pédagogique, des progrès visibles après 3 séances.",
    date: toISODate(addDays(baseWeek, -12)),
  },
  {
    id: "review_6",
    coachId: "coach_5",
    playerName: "Baptiste L.",
    rating: 5,
    comment: "Frappe et finition au top, je suis plus confiant devant le but.",
    date: toISODate(addDays(baseWeek, -9)),
  },
  {
    id: "review_7",
    coachId: "coach_7",
    playerName: "Maya T.",
    rating: 5,
    comment: "Les dribbles et changements de rythme, c'est devenu mon point fort.",
    date: toISODate(addDays(baseWeek, -4)),
  },
  {
    id: "review_8",
    coachId: "coach_8",
    playerName: "Enzo G.",
    rating: 4,
    comment: "Placement défensif amélioré, bons conseils tactiques.",
    date: toISODate(addDays(baseWeek, -7)),
  },
];
